### ISSUE TITLE
Coffee Leak

### ISSUE THREAD

**Issue by josh-dev-things** [mjwakex/Foundations-of-CS#1]
### Jack Cole Coffee Spillage
Some muppet knocked a mug of coffee over in the lecture room _during a live cs2003 lecture._ This issue still hasn't been resolved by @mjwakex and should be seen to swiftly.

Please fix coffee retention before releasing further materials.

**Comment by mjwakex** [comment]
please refrain from leaving unprofessional issues on a public repository next time. This has now been resolved.
